### PR TITLE
add support to vercel edge runtime

### PR DESCRIPTION
**Pull request by bernatvadell**
When compiling new nextjs projects it gives the following error:

```
../../node_modules/.pnpm/reflect-metadata@0.1.13/node_modules/reflect-metadata/Reflect.js
Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Edge Runtime 
Learn More: https://nextjs.org/docs/messages/edge-dynamic-code-evaluation

Import trace for requested module:
../../node_modules/.pnpm/reflect-metadata@0.1.13/node_modules/reflect-metadata/Reflect.js
../../packages/sdk/dist/esm/index.js
```

This is due to the dynamic evaluation of this piece of code in `Reflect.ts`: 
```ts
Function("return this;")();
```
To make it compatible, I've changed it to:
```ts
(() => { return this; })();
```

With this simple change, the project already compiles correctly.

### CODE REVIEW

**Comment by ljharb** [comment]
Those aren’t the same; using Function is the only reliable way to get to the global, since it’s in sloppy mode.

**Comment by rezonant** [comment]
Fascinating. Here's a write-up discussing the difficulties of accessing globalThis portably (even on runtimes that do not have globalThis). 

https://mathiasbynens.be/notes/globalthis

Could we use the same accessor trick to accomplish this while avoiding eval/Function constructor?

**Comment by ljharb** [comment]
Realistically this package should probably use https://npmjs.com/globalthis instead, and then your own bundler could alias it out with whatever env-specific mechanism you need.

**Comment by rezonant** [comment]
I agree it would be better to polyfill outside this module, but we can't just put a require() in there (or include for that matter) without limiting the scope in which the package can be loaded. 

I personally don't have any qualms about simply requiring users to polyfill globalThis themselves if they need to, as long as it would be a major version bump.

**Comment by rbuckton** [comment]
Is this a build failure or a runtime failure? If it's a runtime failure, providing a `globalThis` polyfill would avoid any dynamic evaluation. If it's a build failure, is there any way to exclude `reflect-metadata` from this restriction?

I don't believe I can drop the dynamic evaluation mechanism to acquire a reference to the global object without potentially breaking consumers. However, in `reflect-metadata@0.2.0-pre.0` I recently introduced a "lite" mode that drops the internal `Map`/`Set` polyfill, which is accessed via an alternative import of `import "reflect-metadata/lite";`. I could see modifying "lite" mode to elide dynamic evaluation with the expectation that any necessary polyfills are already installed.

**Pull request closed without merging**
